---
driver:
  name: vagrant
  driver_config:
    http_proxy: <%= ENV['http_proxy'] || nil %>
    https_proxy: <%= ENV['https_proxy'] || nil %>
  vagrantfiles:
    - kitchen_vagrant_block.rb

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  roles_path: ../ansible-os-hardening/
  playbook: tests/test.yml
  http_proxy: <%= ENV['http_proxy'] || nil %>
  https_proxy: <%= ENV['https_proxy'] || nil %>

transport:
  max_ssh_sessions: 1

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: bento/ubuntu-16.04
  - name: ubuntu-18.04
    driver_config:
      box: bento/ubuntu-18.04
  - name: ubuntu-20.04
    driver_config:
      box: bento/ubuntu-20.04
  - name: debian-9
    driver_config:
      box: bento/debian-9
  - name: debian-10
    driver_config:
      box: bento/debian-10
    provisioner:
      ansible_binary_path: "/usr/local/bin"

verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - https://github.com/dev-sec/linux-baseline/

suites:
  - name: os
