---
driver:
  name: docker
  use_sudo: false
  cap_add:
    - SYS_ADMIN
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  run_options:
    tmpfs:
      - /tmp
      - /run
      - /run/lock
  run_command: /sbin/init
  http_proxy: <%= ENV['http_proxy'] || nil %>
  https_proxy: <%= ENV['https_proxy'] || nil %>

transport:
  max_ssh_sessions: 1

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true

  roles_path: ../ansible-os-hardening/
  http_proxy: <%= ENV['http_proxy'] || nil %>
  https_proxy: <%= ENV['https_proxy'] || nil %>
  playbook: tests/test.yml

platforms:
  - name: ubuntu1604-ansible-latest
    driver:
      image: rndmh3ro/docker-ubuntu1604-ansible:latest
      platform: ubuntu
      provision_command:
        - systemctl enable ssh.service

  - name: ubuntu1804-ansible-latest
    driver:
      image: rndmh3ro/docker-ubuntu1804-ansible:latest
      platform: ubuntu
      provision_command:
        - systemctl enable ssh.service

  - name: ubuntu12004-ansible-latest
    driver:
      image: rndmh3ro/docker-ubuntu2004-ansible:latest
      platform: ubuntu
      provision_command:
        - systemctl enable ssh.service

  - name: debian9-ansible-latest
    driver:
      image: rndmh3ro/docker-debian9-ansible:latest
      platform: debian
      provision_command:
        - apt install -y systemd-sysv
        - systemctl enable ssh.service

  - name: debian10-ansible-latest
    driver:
      image: rndmh3ro/docker-debian10-ansible:latest
      platform: debian
      provision_command:
        - apt install -y systemd-sysv
        - systemctl enable ssh.service

verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - https://github.com/dev-sec/linux-baseline
  controls:
    # skip sysctl checks, since they make no sense in docker
    - /^(?!sysctl-|package-07).+/

suites:
  - name: os
