---
- name: check cron.daily aide
  become: 'yes'
  stat:
    path: /etc/cron.daily/aide
  register: aidecron

- name: aide service
  become: 'yes'
  template:
    src: lib/systemd/system/aidecheck.service.j2
    dest: /lib/systemd/system/aidecheck.service
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  when: not aidecron.stat.exists
  tags:
    - aide

- name: aide timer
  become: 'yes'
  template:
    src: lib/systemd/system/aidecheck.timer.j2
    dest: /lib/systemd/system/aidecheck.timer
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  when: not aidecron.stat.exists
  notify:
    - reload systemd
    - enable aidecheck
  tags:
    - aide

- name: add aide Debian dir exclusions
  become: 'yes'
  blockinfile:
    path: /etc/aide/aide.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: 'yes'
    insertafter: EOF
    block: |
      !/var/lib/docker
      !/var/lib/lxcfs
      !/var/lib/private/systemd
      !/var/log/audit
      !/var/log/journal
  when: ansible_os_family == "Debian"
  tags:
    - aide

- name: stat Debian aide.db
  become: 'yes'
  stat:
    path: /var/lib/aide/aide.db
  register: ubuaidedb
  when: ansible_os_family == "Debian"
  tags:
    - aide

- name: initialize Debian aide
  become: 'yes'
  expect:
    command: aideinit
    timeout: null
    responses:
      Question:
        - 'Overwrite /var/lib/aide/aide.db [yN]?': 'y'
        - 'Overwrite existing /var/lib/aide/aide.db.new [Yn]?': 'y'
  when: ansible_os_family == "Debian" and not ubuaidedb.stat.exists
  tags:
    - aide
    - skip_ansible_lint
...
