---
- name: merge package lists
  set_fact:
    packages_merged: "{{ packages_debian + packages_redhat + packages_ubuntu }}"
  tags:
    - packages

- name: pre stat needrestart configuration directory
  become: 'yes'
  stat:
    path: /etc/needrestart/conf.d
  register: needrestart_directory_created

- name: create needrestart directory
  become: 'yes'
  file:
    path: /etc/needrestart/conf.d
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: 'yes'
  when: ("needrestart" in packages_merged) and not needrestart_directory_created.stat.exists
  tags:
    - packages

- name: stat needrestart configuration directory
  become: 'yes'
  stat:
    path: /etc/needrestart/conf.d
  register: needrestart_directory

- name: get needrestart restart value
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  command: grep -Rqo "$nrconf{restart} = 'l';" /etc/needrestart/conf.d/
  register: needrestart_restart_set
  when: needrestart_directory.stat.exists
  changed_when: needrestart_restart_set.rc != 0
  failed_when: needrestart_restart_set.rc > 1

- name: configure needrestart
  become: 'yes'
  lineinfile:
    path: /etc/needrestart/conf.d/00-restart.conf
    line: "$nrconf{restart} = 'l';"
    create: 'yes'
    owner: root
    group: root
    mode: 0644
  when: needrestart_directory.stat.exists and needrestart_restart_set.rc != 0

- name: debian family package installation
  become: 'yes'
  apt:
    name: "{{ packages_debian }}"
    state: present
    install_recommends: 'no'
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages

- name: ubuntu package installation
  become: 'yes'
  apt:
    name: "{{ packages_ubuntu }}"
    state: present
    install_recommends: 'no'
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages

- name: ubuntu update-notifier-common package installation
  become: 'yes'
  apt:
    name: "update-notifier-common"
    state: present
    install_recommends: 'no'
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages

- name: redhat family package installation
  become: 'yes'
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_redhat }}"
  when: ansible_os_family == "RedHat"
  ignore_errors: true
  notify:
    - enable haveged
  tags:
    - dnf
    - packages

- name: debian family package removal
  become: 'yes'
  apt:
    name: "{{ packages_blocklist }}"
    state: absent
    purge: 'yes'
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "Debian"
  ignore_errors: true
  tags:
    - apt
    - packages

- name: redhat family package removal
  become: 'yes'
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ packages_blocklist }}"
  when: ansible_os_family == "RedHat"
  ignore_errors: true
  tags:
    - dnf
    - packages

- name: virtualbox package installation
  become: 'yes'
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: 'no'
  vars:
    packages:
      - virtualbox-guest-dkms
      - virtualbox-guest-utils
  when: ansible_bios_version == "VirtualBox" and
        ansible_distribution == "Ubuntu"
  tags:
    - apt
    - packages
    - virtualbox

- name: vmware package installation
  become: 'yes'
  package:
    name: open-vm-tools
    state: present
  when: ansible_bios_version == "VMWare"
  tags:
    - packages
    - vmware

- name: rng-tools package installation
  become: 'yes'
  package:
    name: rng-tools
    state: present
  when: ansible_local.cpuinfo.rdrand
  tags:
    - rng-tools
    - packages

- name: remove unneeded debian dependency packages
  become: 'yes'
  apt:
    autoclean: 'yes'
    autoremove: 'yes'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages
...
